name: '🔬 CI'

on:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Tests
    steps:
      - name: Actions - Checkout
        uses: actions/checkout@v6

      - name: Actions - Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Dependencies
        uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: bun-${{ hashFiles('bun.lock') }}
          restore-keys: bun-

      - name: Installing Dependencies
        run: bun install --frozen-lockfile

      - name: Checking Types
        run: bun run typecheck

      - name: Checking Lint
        run: bun run lint

      - name: Testing
        run: bun run test

      - name: Building Site
        run: bun run build
